# Generated by Django 3.2.3 on 2021-07-11 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Mini valet', max_length=250)),
                ('details', models.TextField(default='No details available', help_text='Valet details')),
                ('price', models.IntegerField(help_text='Valet price')),
            ],
        ),
        migrations.CreateModel(
            name='ValetEnquirie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='Name', help_text='Your name', max_length=250)),
                ('customer_email', models.EmailField(max_length=250)),
                ('customer_phone', models.CharField(help_text='Phone', max_length=250)),
                ('customer_message', models.TextField(help_text='Your message')),
                ('inquiry_date', models.DateField(auto_now_add=True)),
                ('valet', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vehicles.valet')),
            ],
        ),
    ]
