# Generated by Django 3.2.3 on 2021-07-11 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_valet_valetenquirie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valet',
            name='details',
        ),
        migrations.CreateModel(
            name='ValetFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(default='No details available', help_text='Valet feature', max_length=250)),
                ('valet', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vehicles.valet')),
            ],
        ),
    ]
